services:
  pr0:
    container_name: pr0
    image: hashicorp/${OSS:-vault-enterprise}:${VERSION:-latest}
    volumes:
      - ./configs/config0.hcl:/vault/config/config.hcl
      - ./data/data0:/opt/vault/data
      - ./logs/vault0.log:/vault/logs/vault0.log
    networks:
      - vaulty-net
    ports:
      - "8212:8212"
    cap_add:
      - "IPC_LOCK"
    env_file:
      - ../license.env
    environment:
      - VAULT_ADDR=http://127.0.0.1:8212
    command: server
  pr1:
    container_name: pr1
    image: hashicorp/${OSS:-vault-enterprise}:${VERSION:-latest}
    volumes:
      - ./configs/config1.hcl:/vault/config/config.hcl
      - ./data/data1:/opt/vault/data
      - ./logs/vault1.log:/vault/logs/vault1.log
    networks:
      - vaulty-net
    ports:
      - "8214:8214"
    cap_add:
      - "IPC_LOCK"
    env_file:
      - ../license.env
    environment:
      - VAULT_ADDR=http://127.0.0.1:8214
    command: server
  pr2:
    container_name: pr2
    image: hashicorp/${OSS:-vault-enterprise}:${VERSION:-latest}
    volumes:
      - ./configs/config2.hcl:/vault/config/config.hcl
      - ./data/data2:/opt/vault/data
      - ./logs/vault2.log:/vault/logs/vault2.log     
    networks:
      - vaulty-net
    ports:
      - "8216:8216"
    cap_add:
      - "IPC_LOCK"
    env_file:
      - ../license.env
    environment:
      - VAULT_ADDR=http://127.0.0.1:8216
    command: server
networks:
  vaulty-net:
    name: vaulty-net
    external: true